# Project information

site_name: Infrastructure Identity in AWS
site_short_name: Infrastructure Identity
site_description: 'This hands-on workshop is where you will learn about a number of AWS services that will enable you to securely administer your systems in AWS as we walk through real-world threat scenarios. Learn about the secure administration capabilities of AWS Session Manager, AWS Identity and Access Management and Amazon EC2 Instance Connect.'
site_author: 'aws-security-workshops@amazon.com'
site_url: 'https://infrastructure-identity.awssecworkshops.com/'

# Repository
repo_name: 'aws-samples/aws-infrastructure-identity-workshop'
repo_url: 'https://github.com/aws-samples/aws-infrastructure-identity-workshop'

# Copyright
copyright: '&copy; 2019, Amazon Web Services, Inc. or its affiliates. All rights reserved.'

# Configuration
theme:
  name: 'material'
  logo: 'assets/images/aws_smile_logo.png'
  favicon: 'assets/images/aws-favicon.ico'
  feature:
    tabs: true
  custom_dir: 'docs/theme'

# Customization
extra_css:
  - 'stylesheets/custom.css'
extra:
  social:
    - type: 'home'
      link: 'https://awssecworkshops.com'
    - type: 'shield'
      link: 'https://aws.amazon.com/security/'
    - type: 'twitter'
      link: 'https://twitter.com/awssecurityinfo?lang=en'
    - type: 'rss'
      link: 'https://aws.amazon.com/blogs/security/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details

# Navigation
nav:
  - Overview: 'index.md'
  - 'Module 1: Environment setup': '01-environment-setup.md'
  - 'Module 2: Session Manager': '02-using-AWS-Systems-Manager-Session-Manager.md'
  - 'Module 3: EC2 Instance Connect': '03-using-EC2-Instance-Connect.md'
  - 'Module 4: Cleanup': '04-cleanup.md'
  - Contributing: 'contribute.md'
  - License: 'license.md'
